In [14]:
# Import Modules
import pandas as pd
import openpyxl
from openpyxl.utils import column_index_from_string
import re

# Load files. Manually define variables. 
term_1_file_application_comparative = ""  # Exact file name
term_1_file_application_details = "Applications Reports Details-IR-New-Summer 2025 as of May 01, 2025 (Fake Data).xlsx"

term_2_file_application_comparative = ""
term_2_file_application_details = ""

term_3_file_application_comparative = ""
term_3_file_application_details = ""

term_4_file_application_comparative = ""
term_4_file_application_details = ""

# Load the workbook
wb = openpyxl.load_workbook(term_1_file_application_details, data_only=True)

# Try to match any sheet that resembles "Clean Data"
matched_sheet_name = None
for sheet_name in wb.sheetnames:
    normalized = sheet_name.lower().replace(" ", "")
    if normalized == "cleandata":
        matched_sheet_name = sheet_name
        break

if matched_sheet_name is None:
    raise ValueError(f"No sheet matching 'Clean Data' found. Available sheets: {wb.sheetnames}")

# Load the matched sheet into a pandas DataFrame
df = pd.read_excel(term_1_file_application_details, sheet_name=matched_sheet_name)

# Output confirmation and preview
print(f"Loaded sheet: {matched_sheet_name}")
df.head()

Loaded sheet: Clean data

,CURRICULUM,Population group,School,Department,Curriculum,Year,Population,Applicants,Target,First Name,...,Declined,Pending,Waitlisted,Qualified,Enrollment,Target Met,Visa,Country,Deceased Flag,Student Type
0,ACP,Domestic,School Health & Human Services,Nursing & Allied Health,AdvanceCareParamedic,1,Domestic,864423371.0,NaN,FakeName832,...,NaN,NaN,NaN,NaN,NaN,NaN,CDN,Canada,N,NaN
1,ACP,Domestic,School Health & Human Services,Nursing & Allied Health,AdvanceCareParamedic,1,Domestic,223952995.0,NaN,FakeName368,...,NaN,NODE,NaN,NaN,NaN,NaN,CDN,Canada,N,NaN
2,BAACTD,International,School Business University Studies & Upg,Business Administration,Bus Adm Acct Dip,2,International,735265106.0,NaN,FakeName177,...,NaN,NaN,NaN,ACPT,ENRO,NaN,OVIS,India,N,FULL
3,BAACTD,International,School Business University Studies & Upg,Business Administration,Bus Adm Acct Dip,2,International,397216345.0,NaN,FakeName762,...,NaN,NaN,NaN,ACPT,ENRO,NaN,OVIS,India,N,PART
4,BABUSD,International,School Business University Studies & Upg,Business Administration,Bus Adm Mgmt Dip,2,International,NaN,NaN,FakeName805,...,NaN,NaN,NaN,ACPT,ENRO,NaN,SVIS,India,N,FULL

In [15]:
# Count total applicants (assuming no empty cells)
total_applicants = df['Applicants'].count()

# Count unique applicants (assuming the column contains identifiers for each applicant)
total_unique_applicants = df['Applicants'].nunique()

# Output the results
print(f"Total applicants: {total_applicants}")
print(f"Total unique applicants: {total_unique_applicants}")

# Count how many "Domestic" applicants
domestic_applicants = df[df['Population'] == 'Domestic'].shape[0]

# Count how many "International" applicants
international_applicants = df[df['Population'] == 'International'].shape[0]

# Output the results
print(f"Total Domestic applicants: {domestic_applicants}")
print(f"Total International applicants: {international_applicants}")

Total applicants: 48
Total unique applicants: 48
Total Domestic applicants: 24
Total International applicants: 25

In [ ]:

valid_accepted = ["ACPT", "COND", "ACLN"]
excluded_deferred = ["ACPT", "COND"]

# Apply the filters
filtered_df = df[
    df["Accepted"].isin(valid_accepted) &
    ~df["Deffered Application"].isin(excluded_deferred) #Fix spelling once Alka fixes
]

count = len(filtered_df)
print(f"Valid application count: {count}")

Valid application count: 43